version: '3'

services:
  website:
    image: symkat/housenewswire:latest
    container_name: hnw-web
    ports:
        - 5000:5000
    volumes:
      - ./.docker/housenewswire/dbic.yaml:/app/dbic.yaml:ro
  database:
    image: postgres:11
    container_name: hnw-db
    ports:
        - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=housenewswire
      - POSTGRES_USER=housenewswire
      - POSTGRES_DB=housenewswire
    volumes:
      - ./Database/etc/schema.sql:/docker-entrypoint-initdb.d/000_schema.sql:ro
      - database:/var/lib/postgresql/data

volumes:
  database:
